# Generated by Django 3.2.9 on 2021-11-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='info',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='info',
            new_name='phone',
        ),
    ]
